### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by MattiSG** [sgmap/dashboard#1]
This dashboard is specific to API Entreprise, but is hosted in the `sgmap` organisation. Its simple “dashboard” name is thus misleading, as it seems to entail that it's a dashboard common to the whole incubator.

Renaming to something like “apientreprise-dashboard” would remove this ambiguity.

**Comment by jdesboeufs** [comment]
Moreover, API Entreprise repository should now land on the `etalab` organization ;)

**Comment by brindu** [comment]
I agree ! Can I have an invitation on the etalab organization ? :)

**Comment by brindu** [comment]
Sources are now hosted here : https://github.com/etalab/dashboard_apientreprise. 
I will now remove this repo.
